export const WORDS = [
    "APPLE", "GRAPE", "MANGO", "PLUMB", "BRAVE", "PLANT", "CRISP", "SHOCK", "TREND", "FLOOR",
    "BREAD", "CHAIR", "BLEND", "QUICK", "FRUIT", "STORM", "PLAZA", "SCALE", "SLICE", "SPARK",
    "CLOUD", "GLOVE", "SHINE", "BRUSH", "SMILE", "GRASS", "WINGS", "TRAIN", "DREAM", "FLARE",
    "STONE", "HAPPY", "TABLE", "LIGHT", "WATER", "RIVER", "MOUSE", "EARTH", "PLANE", "PLUMB",
    "CLEAN", "CHAOS", "CROWN", "DANCE", "DRIFT", "EAGER", "EAGLE", "FAITH", "FORCE", "GLASS",
    "GREEN", "GUARD", "HEART", "HONOR", "JOLLY", "KNEEL", "LATCH", "LEMON", "MAGIC", "NOBLE",
    "OCEAN", "ORDER", "PAUSE", "PEACE", "POWER", "QUEST", "RAPID", "REACT", "SILKY", "SLOPE",
    "SOLID", "TOWER", "UNCLE", "VIVID", "WORTH", "YOUTH", "ALERT", "BASIN", "CANDY", "DAISY",
    "ELDER", "FABLE", "GRACE", "HUMOR", "IVORY", "JUMBO", "KNACK", "LAUGH", "MIRTH", "NIGHT",
    "OPERA", "PAINT", "QUICK", "RANGE", "SPOON", "TIGER", "UPPER", "VALVE", "WITCH", "YEARN",
    "ZEBRA", "BLAZE", "CHIME", "DOUBT", "EQUAL", "FRESH", "GUILD", "HONEY", "INFER", "JOLLY",
    "KINDY", "LEVEL", "MUSIC", "NEVER", "OFFER", "PIVOT", "QUILT", "RAISE", "SHOUT", "TASTE",
    "UNTIE", "VOUCH", "WATCH", "YIELD", "ZONAL", "ANGRY", "BEACH", "CLOVE", "DENSE", "EVENT",
    "FEAST", "GREAT", "HATCH", "INNER", "JUMPY", "KARMA", "LUNCH", "MERRY", "NASTY", "OPTIC",
    "PEBBL", "QUIRK", "REBEL", "SHARP", "THUMB", "URBAN", "VOICE", "WOVEN", "XENON", "ZIPPY",
    "ABIDE", "BERRY", "CIVIC", "DEALT", "EPOCH", "FROST", "GHOST", "HOUSE", "INDEX", "JOLLY",
    "KNOCK", "LUCKY", "MANGO", "NOVEL", "ORDER", "PLUMB", "QUIET", "ROUND", "SHOCK", "TOUCH",
    "UPSET", "VISIT", "WORST", "YOUNG", "ZEBRA", "AHEAD", "BLADE", "CATCH", "DIZZY", "EAGER",
    "FAULT", "GLOOM", "HEARD", "IMAGE", "JUICE", "KNIFE", "LEARN", "MARCH", "NOBLE", "OZONE",
    "PLUMB", "QUIRK", "RUSHY", "SPLIT", "THINK", "UNITE", "VIGOR", "WISER", "XENON", "YACHT"
  ];
  